"""Add accepted to trip_invites

Revision ID: 1fc51cc70b43
Revises: 30e94d25e698
Create Date: 2025-11-21 19:46:09.800428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc51cc70b43'
down_revision = '30e94d25e698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invites', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
