"""Renamed long to lon in Trip model

Revision ID: 30e94d25e698
Revises: a083e0cab8f1
Create Date: 2025-11-17 21:24:27.274466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e94d25e698'
down_revision = 'a083e0cab8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=False))
        batch_op.alter_column('activities',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.drop_column('long')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long', sa.FLOAT(), nullable=False))
        batch_op.alter_column('activities',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('lon')

    # ### end Alembic commands ###
