"""empty message

Revision ID: 3c801a59792f
Revises: b9e9bf056852
Create Date: 2025-11-13 14:22:46.049127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c801a59792f'
down_revision = 'b9e9bf056852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('long', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('long')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
