"""Add destination, activities, notes to Trip model

Revision ID: a083e0cab8f1
Revises: 3c801a59792f
Create Date: 2025-11-17 20:40:26.592110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a083e0cab8f1'
down_revision = '3c801a59792f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('activities', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('activities')
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
